services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydb'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
#services:
#  app:
#    build: .
#    container_name: spring-app
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
#      - SPRING_DATASOURCE_USERNAME=vasu
#      - SPRING_DATASOURCE_PASSWORD=root
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    networks:
#      - app-network
#
#  db:
#    image: postgres:latest
#    container_name: postgres-db
#    environment:
#      - POSTGRES_DB=mydb
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=root
#    ports:
#      - "5432:5432"
#    networks:
#      - app-network
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#
#networks:
#  app-network:
#    driver: bridge
#
#volumes:
#  postgres-data:
#    driver: local